apiVersion: v1
kind: Pod
metadata:
  name: apache-http
  labels:
    app: apache
    env: dev
spec:
  containers:
  - name:  apache-http
    image: httpd:latest
    securityContext:
      privileged: true
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: logs
      mountPath: /usr/local/apache2/logs
    ports:
    - containerPort: 80
    - containerPort: 443
    env:
    - name: APP_COLOR
  volumes:
  - name: logs
    emptyDir: {}   
